name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      Tag:
        description: 'Tag'
        required: true
        default: '@a'
        type: choice
        options:
          - '@a'
          - '@b'
          - '@c'

jobs:
  first:
    if: ${{ github.event.inputs.Tag == '@a' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  second:
    if: ${{ github.event.inputs.Tag == '@b' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  third:
    if: ${{ github.event.inputs.Tag == '@c' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
