name: Simple Action
on: [push, workflow_dispatch]

jobs:
  simple-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send a joke on slack
        uses: ./.github/actions/slack-joke
        with:
          slack_username: Andrew
          upload_joke: true
          slack_webhook: