name: Calling Reusable Workflows
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Input description"
        type: string
        default: "Ali"
        required: false
jobs:
  calling-a-reusable-wf:
    uses: aksellyactionscourse/workflow/.github/workflows/reusable.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}
  calling-a-reusable-workflow-in-same-repo:
    uses: ./.github/workflows/reusable-workflow.yaml
  using-reusable-wf-output:
    runs-on: ubuntu-latest
    needs: calling-a-reusable-workflow-in-same-repo
    steps:
      - run: echo ${{ needs.calling-a-reusable-workflow-in-same-repo.outputs.date }}